Feat/main page
bakalux/twitter-demo-frontend pull request #1
Opened 2018-06-15 08:59 UTC by bakalux

Добавил страницу пользователя
Добавил редирект с / на /everyinteract

2018-06-15 22:52 UTC, imevro requested changes

2018-06-15 22:52 UTC, evgenyrodionov commented on src/App.js
> +import {BrowserRouter, Route, Redirect, Switch} from "react-router-dom";
![image](https://user-images.githubusercontent.com/775692/41492461-f504a8fa-7107-11e8-9b80-eacbf2f549be.png)

2018-06-16 20:57 UTC, bakalux commented
Добавил отзывчивость кнопок.
Исправил отображение картинки в Article.
Добавил пропсы к Statistics, разместил Statistics и Header в отдельные файлы.

2018-06-18 06:40 UTC, imevro requested changes

2018-06-18 06:40 UTC, evgenyrodionov commented on src/App.js
> +import Everyinteract from "./Everyinteract";
а для моего аккаунта в твиттере ты заведёшь отдельный файл EvgenyRodionov.js?

2018-06-18 06:40 UTC, evgenyrodionov commented on src/App.js
> +            render={() => <Redirect to="/everyinteract" />}
если прочитать документацию реакт-роутера внимательно, то можно заметить что там есть проп `from`

2018-06-18 06:40 UTC, evgenyrodionov commented on src/App.js
> +        <Switch>
объясни зачем ты используешь свитч

это вопрос

2018-06-18 06:40 UTC, evgenyrodionov commented on src/Header.js
> +import HomeIcon from "./icons/Icon_Home.svg";
почему у тебя иконки называются как будто это компоненты? ты частые ошибки читал? раздел про нейминг

2018-06-18 06:40 UTC, evgenyrodionov commented on src/Header.js
> +import { TweetButton, NavLink } from "./Everyinteract";
почему ты навлинк импортишь из страницы профиля? втф?

2018-06-18 06:40 UTC, evgenyrodionov commented on src/Header.js
> +import { TweetButton, NavLink } from "./Everyinteract";
почему хедер (более общее) лезет в страницу профиля (частное)?

2018-06-18 06:40 UTC, evgenyrodionov commented on src/Statistics.js
> +class Statistics extends Component {
зачем ты используешь класс?

2018-06-18 06:40 UTC, evgenyrodionov commented on src/icons/EI Avatar.svg
> +<image id="image0" width="400" height="400" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAYAAACAvzbMAAAAAXNSR0IArs4c6QAAGAxJREFUeAHt3VnMXlP7B+DV4jNG1FAhSEhUJRygQQQxpMGJkEgFFWMl1
если это пнг, почему ты используешь его как свг?

2018-06-18 22:21 UTC, bakalux commented
Исправил ошибки.
Вынес TweetButton в отдельный файл.
Сделал ProfileCard и Tweet с пропами

2018-06-19 11:02 UTC, imevro requested changes

2018-06-19 11:02 UTC, evgenyrodionov commented on src/App.js
> +const RoutingToProfilePage = () => {
зачем? усложняешь на пустом месте

2018-06-19 11:02 UTC, evgenyrodionov commented on src/ProfileCard.js
> +      </CardListItem>
хуитем

2018-06-19 11:02 UTC, evgenyrodionov commented on src/ProfilePage.js
> +  top: 42%;
зачем ты проценты делаешь? не надо так делать

2018-06-19 11:02 UTC, evgenyrodionov commented on src/ProfilePage.js
> +          <div class="col-xl-offset-1 col-lg-offset-1" />
1) оффсеты не так используются
2) откуда тут класс

2018-06-19 11:02 UTC, evgenyrodionov commented on src/ProfilePage.js
> +class ProfilePage extends Component {
зачем ты класс используешь?

2018-06-23 18:32 UTC, bakalux commented
Исправил ошибки.
Добавил новые роутинг для внутренних ссылок
Добавил новые блоки с пропами
Добавил хелмет

2018-06-25 15:48 UTC, imevro requested changes

2018-06-25 15:48 UTC, evgenyrodionov commented on debug.log
> +[0623/004958.748:ERROR:crash_report_database_win.cc(428)] unexpected header
что это

2018-06-25 15:48 UTC, evgenyrodionov commented on src/ProfilePage.js
> +  top: 43vh;
нет, вообще ненадежно верстаешь

2018-06-25 15:49 UTC, evgenyrodionov commented on src/ProfilePage.js
> +  top: 43vh;
абсолюты вообще не для этого

2018-06-25 15:49 UTC, evgenyrodionov commented
Как исправишь — сделай мердж через сквош (это мердж, который все коммиты в бранче схлопывает в один)

Не забудь сделать гит пулл перед тем как стартовать новые ветки от мастера

Если уже делал новую ветку от этой, то коммитни изменения, сделай новую от мастера и туда черри-пиком и забери коммиты

Напиши мне в телеграм с ссылкой на этот пуллреквест, добавлю в курсач и второй этап

2018-06-27 09:58 UTC, merged